version: '3.5'

services:
  kotlin-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: anri
      POSTGRES_USER: anri
      POSTGRES_DB: warung-db
